AirTecFugas/AirTecFugas/urls.py
"""
Definition of urls for AirTecFugas.
"""

from datetime import datetime
from django.conf.urls import url
from django.conf.urls import re_path
import django.contrib.auth.views
import MainApp
import WebApiApp

# Uncomment the next lines to enable the admin:
from django.conf.urls import include
from django.contrib import admin
admin.autodiscover()

urlpatterns = [# Examples:
    re_path(r'^', include('MainApp.urls')),
    re_path(r'^api/', include('WebApiApp.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    re_path(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    re_path(r'^admin/', admin.site.urls),]

AirTecFugas/MainApp/urls.py
"""
Definition of urls for AirTecFugas.
"""

from datetime import datetime
from django.conf.urls import url
from django.conf.urls import re_path
import django.contrib.auth.views
from django.conf import settings
from django.conf.urls.static import static

from MainApp.forms import BootstrapAuthenticationForm
from MainApp.views import default
from MainApp.views.FugaViews import FugaCreateView, FugaListView, FugaDetailsViews, FugaEditView, FugaDeleteView, FugaExportCSVFormView
from MainApp.views.AreaViews import AreaCreateView, AreaCreatePartialView, AreaListView, AreaEditsView, AreaDeleteView
from MainApp.views.MaquinaViews import MaquinaCreateView, MaquinaCreatePartialView, MaquinaListView, MaquinaEditViews, MaquinaDeleteView
from MainApp.views.PlantaViews import SeleccionPlantaTrabajoView, CreatePlantaPartialView, PlanoPlantaView, PlanoPlantaImgView
from MainApp.views.EmpresaViews import CreateEmpresaPartialView
from MainApp.views.ImagenFugaViews import DetailImagenView
from MainApp.views.Mapa.MapaOpenLayerViews import MapaFugasOpenLayerView

# Uncomment the next lines to enable the admin:
from django.conf.urls import include
from django.contrib import admin
admin.autodiscover()

urlpatterns = [# Examples:
    re_path(r'^$', default.home, name='home'),
    re_path(r'^dashboard/$', default.dashboard, name='dashboard'),
    re_path(r'^contact$', default.contact, name='contact'),
    re_path(r'^about$', default.about, name='about'),

    ### -------------- CRUD EMPRESA -------------- ###
    re_path(r'^empresa/create/$', CreateEmpresaPartialView.as_view(), name='empresa-create'),
    #re_path(r'^empresa/edit/(?P<pk>\d+)/$', default.about,
    #name='empresa-edit'),
    #re_path(r'^empresa/details/(?P<pk>\d+)/$', default.about,
    #name='empresa-details'),
    re_path(r'^empresa/list/$', default.about, name='empresa-list'),

    ### -------------- CRUD PLANTA -------------- ###
    re_path(r'^planta/seleccionar-planta/$', SeleccionPlantaTrabajoView.as_view(), name='selec-planta-trabajo'),
    re_path(r'^planta/plano/(?P<pk>\d+)/$', PlanoPlantaView.as_view(), name='planta-plano-view'),
    re_path(r'^planta/plano_img/(?P<pk>\d+)/$', PlanoPlantaImgView.as_view(), name='planta-plano-view'),
    re_path(r'^planta/create/$', CreatePlantaPartialView.as_view(), name='planta-create'),
    re_path(r'^planta/list/$', default.about, name='planta-list'),

    ### -------------- CRUD FUGA -------------- ###
    re_path(r'^mapa-fugas/$', default.mapafugas, name='mapa-fugas'),

    re_path(r'^mapafugas/$', MapaFugasOpenLayerView.as_view(), name='mapa-fugas-ol'),

    re_path(r'^fuga/create/(?P<punto_x>-?\d+\.\d+)/(?P<punto_y>-?\d+\.\d+)/$', FugaCreateView.as_view(), name='fuga-create'),
    re_path(r'^fuga/edit/(?P<pk>\d+)/$', FugaEditView.FugaEditView.as_view(), name='fuga-edit'),
    #re_path(r'^fuga/edit/mapa/(?P<pk>\d+)/$', FugaEditView, name='fuga-edit'),
    re_path(r'^fuga/delete/(?P<pk>\d+)/$', FugaDeleteView.as_view(), name='fuga-delete'),
    re_path(r'^fuga/partial-edit/(?P<pk>\d+)/$', FugaEditView.FugaPartialEditView.as_view(), name='fuga-partial-edit'),
    re_path(r'^fuga/corregida/(?P<pk>\d+)/$', FugaEditView.FugaCorregidaEditView.as_view(), name='fuga-corregida'),
    re_path(r'^fuga/details/(?P<pk>\d+)/$', FugaDetailsViews.FugaDetailView.as_view(), name='fuga-details'),
    re_path(r'^fuga/partial-details/(?P<pk>\d+)/$', FugaDetailsViews.FugaDetailPartialView.as_view(), name='fuga-partial-details'),
    re_path(r'^fuga/imagenes/(?P<pk>\d+)/$', FugaDetailsViews.ImagenesFugaDetailView.as_view(), name='fuga-images'),
    re_path(r'^fuga/list/$', FugaListView.as_view(), name='fuga-list'),
    re_path(r'^fuga/export/csv/$', FugaExportCSVFormView.as_view(), name='fuga-export-csv'),

    ### -------------- CRUD AREA -------------- ###
    re_path(r'^area/create/$', AreaCreateView.as_view(), name='area-create'),
    re_path(r'^area/partial-create/$', AreaCreatePartialView.as_view(), name='area-create-partial'),

    re_path(r'^area/partial-edit/(?P<pk>\d+)/$', AreaEditsView.AreaPartialEditView.as_view(), name='area-partial-edit'),
    re_path(r'^area/partial-delete/(?P<pk>\d+)/$', AreaDeleteView.as_view(), name='area-delete'),
    re_path(r'^area/list/$', AreaListView.as_view(), name='area-list'),

    ### -------------- CRUD MAQUINA -------------- ###
    re_path(r'^maquina/create/$', MaquinaCreateView.as_view(), name='maquina-create'),
    re_path(r'^maquina/partial-create/$', MaquinaCreatePartialView.as_view(), name='maquina-create-partial'),

    re_path(r'^maquina/partial-edit/(?P<pk>\d+)/$', MaquinaEditViews.MaquinaPartialEditView.as_view(), name='maquina-partial-edit'),
    re_path(r'^maquina/partial-delete/(?P<pk>\d+)/$', MaquinaDeleteView.as_view(), name='maquina-partial-delete'),
    re_path(r'^maquina/list/$', MaquinaListView.as_view(), name='maquina-list'),

    ### -------------- IMAGENES FUGA -------------- ###
    re_path(r'^imagen-fuga/detail/(?P<pk>\d+)/$', DetailImagenView.as_view(), name='imagen-fuga-view'),

    re_path(r'^login/$',django.contrib.auth.views.LoginView.as_view(template_name= 'MainApp/Authentication/login.html', 
                                                    authentication_form= BootstrapAuthenticationForm,
                                                    redirect_authenticated_user=True,
                                                    extra_context={ 'title': 'Log in', 'year': datetime.now().year,}),name = 'login'),
    re_path(r'^logout$', django.contrib.auth.views.LogoutView.as_view(),name = 'logout')]

AirTecFugas/ModelsApp/models/Fuga.py
# -*- coding: utf-8 -*-
from django.db import models
from .BaseModel import BaseModel
from .Area import Area
from .Maquina import Maquina
from .Ubicacion import Ubicacion
from .User import User
# from .ImagenFuga import ImagenFuga
from django.utils.encoding import python_2_unicode_compatible

@python_2_unicode_compatible
class Fuga(BaseModel):
    """ Model to represents the abstract object called Fuga """

    # Categorias
    categorias = ((1,"1"),(2,"2"),(3, "3"))
    categorias_dict = [{"id":1, "nombre": "1"},{"id":2, "nombre": "2"},{"id":3, "nombre": "3"}]
    # Recomendaciones de la fuga
    recomendaciones = (("REP", "Reparar"),("REM","Remplazar"),("OTR", "Otra"))
    recomendaciones_dict = [{"id":"REP", "nombre":"Reparar"},{"id":"REM", "nombre":"Remplazar"},{"id":"OTR", "nombre": "Otra"}]
    # Estatus de la fuga
    estatus_fuga = ((1, "Registrado"),(2,"Corregido"))
    estatus_fuga_dict = [{"id":1, "nombre":"Registrado"},{"id":2,"nombre":"Corregido"}]

    area = models.ForeignKey(Area, on_delete=models.PROTECT, verbose_name="Área")
    maquina = models.ForeignKey(Maquina, on_delete=models.PROTECT, verbose_name="Máquina")
    ubicacion = models.ForeignKey(Ubicacion, on_delete=models.PROTECT, verbose_name="Ubicación")
    categoria = models.SmallIntegerField("Categoría", choices=categorias)
    recomendacion = models.CharField("Recomendación", max_length=3, choices=recomendaciones) 
    refacciones_comentarios = models.CharField("Refacciones y/o comentarios", max_length=1000, blank=True, null=True)
    nadp = models.BooleanField("Not Available During Production (NADP)", default=False)
    estatus = models.SmallIntegerField("Estatus", default=1, choices=estatus_fuga)
    tecnico = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name="Técnico Registró")
    punto_x = models.DecimalField(verbose_name="Coordenada X", max_digits=26, decimal_places=18)
    punto_y = models.DecimalField(verbose_name="Coordenada Y", max_digits=26, decimal_places=18)

    @property
    def imagenes(self):
        return self.imagenfuga_set.filter(is_enabled=True)
        #return ImagenFuga.objects.filter(fuga__id=self.pk, is_enabled=True)

    def to_csv_row(self):
        return [self.area.nombre, self.maquina.nombre, self.ubicacion.nombre, self.categoria
                , self.recomendacion_csv, self.estatus_csv, self.nadp_csv, self.refacciones_comentarios
                , self.flujo, self.ahorro_economico, self.ahorro_energetico]

    @property
    def recomendacion_csv(self):
        if self.recomendacion == "REP":
            return "Reparar"
        elif self.recomendacion == "REM":
            return "Remplazar"
        elif self.recomendacion == "OTR":
            return "Otra"

    @property
    def estatus_csv(self):
        if self.estatus == 1:
            return "Registrado"
        elif self.estatus == 2:
            return "Corregido"

    @property
    def nadp_csv(self):
        return "Si" if self.nadp else "No"

    @property
    def flujo(self):
        return (float(self.categoria) * 1.2)

    @property
    def ahorro_economico(self):
        horas_totales = float(self.area.planta.horas_totales)
        return (((self.flujo * 60 * horas_totales) / 1000) * 0.42)

    @property
    def ahorro_energetico(self):
        horas_totales = float(self.area.planta.horas_totales)
        return ((self.flujo / 4) * 0.7459 * horas_totales)

    #Custom Methods
    def __str__(self):
        return u"Fuga: " + str(self.id)


    def __unicode__(self):
        return u"Fuga: " + str(self.id)

AirTecFugas/ModelsApp/models/Maquina.py
# -*- coding: utf-8 -*-
from django.db import models
from .BaseModel import BaseModel
from .Area import Area
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible
class Maquina(BaseModel):
    """ Model to represent the abstract object called Maquina """
    nombre = models.CharField("Nombre", max_length=50)
    descripcion = models.CharField("Descripción", max_length=500, blank=True, null=True)
    area = models.ForeignKey(Area, on_delete=models.PROTECT, verbose_name="Área")

    # Custom Methods
    def __str__(self):
        return u"" + self.nombre


    def __unicode__(self):
        return u"" + self.nombre

AirTecFugas/MainApp/forms/BootstrapAuthenticationForm.py
"""
Definition of forms.
"""

from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _

class BootstrapAuthenticationForm(AuthenticationForm):
    """Authentication form which uses boostrap CSS."""
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'User name'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Password'}))

AirTecFugas/MainApp/views/default.py
"""
Definition of views.
"""

from django.shortcuts import render, redirect
from django.http import HttpRequest
from django.template import RequestContext
from django.contrib.auth.decorators import permission_required, login_required
from datetime import datetime
from MainApp.logic import PlantaLogicB


def home(request):
    """Renders the home page."""
    assert isinstance(request, HttpRequest)
    if not request.user.is_authenticated:
        return render(request,
            'MainApp/Home/index.html',
            {
                'title':'Home Page',
                'year':datetime.now().year,
            })
    else:
        return redirect('dashboard')

@login_required
def dashboard(request):
    """Renders the home page."""
    cliente = request.session.get("id_cliente",None)
    id_planta = request.session.get("id_planta",None)

    if cliente != None and id_planta != None:
        planta = PlantaLogicB.get_planta(id_planta)

        datos = PlantaLogicB.get_dashboard_stats(id_planta, planta)

        total_fugas = datos[0]
        fugas_resueltas = datos[1]
        porcentaje_fugas = datos[2]
        ahorro_economico = datos[3]
        ahorro_energetico = datos[4]
        emisiones_co2 = datos[5]

        return render(request, 'MainApp/Dashboard/dashboard.html',
            {
                'title':'Dashboard',
                'year':datetime.now().year,
                'menu':"DASHBOARD",
                'total_fugas': total_fugas,
                'fugas_resueltas':fugas_resueltas,
                'porcentaje_fugas':porcentaje_fugas,
                'ahorro_economico':ahorro_economico,
                'ahorro_energetico': ahorro_energetico,
                'emisiones_co2':emisiones_co2
            })
    else:
        return redirect("selec-planta-trabajo")

def contact(request):
    """Renders the contact page."""
    assert isinstance(request, HttpRequest)
    return render(request,
        'MainApp/contact.html',
        {
            'title':'Contact',
            'message':'Your contact page.',
            'year':datetime.now().year,
        })

def about(request):
    """Renders the about page."""
    assert isinstance(request, HttpRequest)
    return render(request,
        'MainApp/about.html',
        {
            'title':'About',
            'message':'Your application description page.',
            'year':datetime.now().year,
        })

@login_required
@permission_required('ModelsApp.view_fuga')
def mapafugas(request):
    """Renders the about page."""
    cliente = request.session.get("id_cliente",None)
    planta = request.session.get("id_planta",None)

    if cliente != None and planta != None:
        assert isinstance(request, HttpRequest)
        return render(request,
            'MainApp/Fuga/mapa-fugas.html',
            {
                'title':'Mapa fugas',
                'message':'Your application description page.',
                'year':datetime.now().year,
            })
    else:
        return redirect("selec-planta-trabajo")

AirTecFugas/WebApiApp/views/MaquinaViews.py
# -*- coding: utf-8 -*-
from ModelsApp.models import Maquina
from rest_framework import viewsets
from WebApiApp.serializers.MaquinaSerializers import MaquinaSelectSerializer

class MaquinaListSelectView(viewsets.ModelViewSet):
    """ View to returns list of Ubicaciones with a form for Select Control """
    serializer_class = MaquinaSelectSerializer
    
    def get_queryset(self):
        id_area = self.kwargs.get('id_area',None)
        queryset = Maquina.objects.filter(is_enabled=True, area__id=id_area).order_by('nombre') if id_area is not None else Maquina.objects.filter(is_enabled=True).order_by('nombre')
        return queryset

AirTecFugas/MainApp/templates/MainApp/Maquina/create-maquina-partial.html
<div class="row gutters">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
        <div class="card">
            <div class="card-header">Registrar Nueva M&aacute;quina</div>
            <div class="card-body">
                <form id="idFormCreateNewMachine" name="FormCreateNewMachine" action="{% url 'maquina-create' %}" method="post">
                    {% csrf_token %}
                    {% for field in form.visible_fields  %}
                        {% if field.field.widget.input_type != "checkbox" %}
                            <div class="form-group">
                                {{ field.label_tag }}
                                {{ field }}
                                {% if field.help_text %}
                                    <div class="alert alert-light" role="alert">
                                        {{ field.help_text|safe }}
                                    </div>
                                {% endif %}
                                {% if field.errors %}
                                    <div class="alert alert-warning" role="alert">
                                        {{ field.errors }}
                                    </div>
                                {% endif %}
                            </div>
                        {% else %}
                            <div class="form-group">
                                <div class="form-check">
                                    <label class="form-check-label">
                                        {{ field }}
                                        {{ field.label }}
                                    </label>
                                </div>
                                {% if field.help_text %}
                                    <div class="alert alert-light" role="alert">
                                        {{ field.help_text|safe }}
                                    </div>
                                {% endif %}
                                {% if field.errors %}
                                    <div class="alert alert-warning" role="alert">
                                        {{ field.errors }}
                                    </div>
                                {% endif %}
                            </div>
                        {% endif %}
                    {% endfor %}
                    {% if form.hidden_fields %}
                        {{ form.hidden_fields }}
                    {% endif %}
                    <button type="submit" class="btn btn-primary"><i class="icon-save2"></i>&nbsp; Guardar M&aacute;quina </button>
                </form>
            </div>
        </div>
    </div>
</div>

AirTecFugas/MainApp/templates/MainApp/Maquina/create-maquina.html
{% extends "MainApp/Layout/_Layout.html" %}

{% block content %}

<div class="row gutters">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
        <div class="card">
            <div class="card-header">Registrar Nueva M&aacute;quina</div>
            <div class="card-body">
                <form action="{% url 'maquina-create' %}" method="post">
                    {% csrf_token %}
                    {% for field in form.visible_fields  %}
                        {% if field.field.widget.input_type != "checkbox" %}
                            <div class="form-group">
                                {{ field.label_tag }}
                                {{ field }}
                                {% if field.help_text %}
                                    <div class="alert alert-light" role="alert">
                                        {{ field.help_text|safe }}
                                    </div>
                                {% endif %}
                                {% if field.errors %}
                                    <div class="alert alert-warning" role="alert">
                                        {{ field.errors }}
                                    </div>
                                {% endif %}
                            </div>
                        {% else %}
                            <div class="form-group">
                                <div class="form-check">
                                    <label class="form-check-label">
                                        {{ field }}
                                        {{ field.label }}
                                    </label>
                                </div>
                                {% if field.help_text %}
                                    <div class="alert alert-light" role="alert">
                                        {{ field.help_text|safe }}
                                    </div>
                                {% endif %}
                                {% if field.errors %}
                                    <div class="alert alert-warning" role="alert">
                                        {{ field.errors }}
                                    </div>
                                {% endif %}
                            </div>
                        {% endif %}
                    {% endfor %}
                    {% if form.hidden_fields %}
                        {{ form.hidden_fields }}
                    {% endif %}
                    <button type="submit" class="btn btn-primary"><i class="icon-save2"></i>&nbsp; Guardar M&aacute;quina </button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

AirTecFugas/MainApp/templates/MainApp/Maquina/delete-maquina.html
<form id="idFormDeleteMaquina" name="FormDeleteMaquina" method="post" action="{% url 'maquina-partial-delete' object.pk %}">
    <div id="GenericModalHeader" class="modal-header">
	    <h5 class="modal-title" id="GenericModalTitle">Confirmaci&oacute;n Borrar M&aacute;quina</h5>
	    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
		    <span aria-hidden="true">×</span>
	    </button>
    </div>
    <div id="GenericModalBody" class="modal-body">
        <div class="row gutters">
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
                <div class="card">
                
                    <div class="card-body">
                        {% csrf_token %}
                        <div class="row gutters">
                            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 text-center">
                                <h5 class="text-danger">
                                    ¿Está seguro que desea borrar la M&aacute;quina?
                                </h5>
                            </div>
                        </div>

                        <hr />

                        <div class="row gutters">
                            <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12">
                                <div class="form-group">
                                    <label for="id_area">Nombre:</label>
                                    <div class="input-group form-group">
                                        <input type="text" value="{{ object.nombre }}" class="form-control" disabled readonly/>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12">
                                <div class="form-group">
                                    <label for="id_maquina">&Aacute;rea:</label>
                                    <div class="input-group form-group">
                                        <input type="text" value="{{ object.area.nombre }}"  class="form-control" disabled readonly/>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row gutters">
                            <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12">
                                <div class="form-group">
                                    <label for="id_ubicacion">Descripci&oacute;n:</label>
                                    <input type="text" value="{{ object.descripcion|default_if_none:"" }}"  class="form-control" disabled readonly/>
                                </div>
                            </div>
                            <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>		
    </div>

    <div id="GenericModalFooter" class="modal-footer">
        <button type="submit" class="btn btn-primary">
            <i class="icon-trash"></i>&nbsp;Eliminar
        </button>
        <button type="button" class="btn btn-danger" data-dismiss="modal">
            <i class="icon-cancel"></i>&nbsp;Cancelar
        </button>
    </div>

</form>

AirTecFugas/MainApp/templates/MainApp/Maquina/list-maquina.html
{% extends "MainApp/Layout/_Layout.html" %}

{% load staticfiles %}

{% load humanize %}

{% block content %}

<div class="row gutters">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
        <div class="card">
            <div class="card-header">
                <span class="icon-book-open"></span>
                Listado de M&aacute;quinas
            </div>
            <div class="card-body">
                <!--
                <div class="table-responsive">
                    -->
                    <table id="TableMaquinaList" class="table table-striped table-bordered table-responsive">
                        <thead>
                            <tr>
                                <th>
                                    M&aacute;quina
                                </th>
                                <th>
                                    &Aacute;rea
                                </th>
                                <th>
                                    Descripci&oacute;n
                                </th>
                                <th>
                                    Fecha Registro
                                </th>
                                <th>
                                    Acciones
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for maquina in object_list %}
                                <tr class="{% if maquina.estatus == 1 %}table-danger{% elif maquina.estatus == 2 %}table-success{% endif %}">
                                    <td>
                                        {{ maquina.nombre }}
                                    </td>
                                    <td>
                                        {{ maquina.area.nombre }}
                                    </td>
                                    <td>
                                        {{ maquina.descripcion|default_if_none:"" }}
                                    </td>
                                    <td>
                                        {{ maquina.added|date }}
                                    </td>
                                    <td>
                                        <button type="button" class="btn btn-dark" data-toggle="modal" data-target="#genericModal" data-action="EditMaquina" data-url="{% url 'maquina-partial-edit' maquina.pk %}">
                                            <span class="icon-edit2"></span>&nbsp;Editar
                                        </button>
                                        <button class="btn btn-secondary"  data-toggle="modal" data-target="#genericModal" data-action="DeleteMaquina" data-url="{% url 'maquina-partial-delete' maquina.pk %}">
                                            <span class="icon-trash"></span>&nbsp;Eliminar
                                        </button>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                <!--
                </div>
                -->
            </div>
        </div>
    </div>
    <input id="idUrlApiAreaListSelect" name="UrlApiAreaListSelect" type="hidden" value="{% url 'ApiAreaListSelect' %}" />
    <input id="idUrlMaquinaList" name="UrlAreaList" type="hidden" value="{% url 'maquina-list' %}" />
</div>

{% include "MainApp/Modals/_GenericModalSinCont.html" %}

{% endblock %}

{% block scripts %}

{% endblock %}

{% block finalscripts %}

<script src="{% static 'MainApp/scripts/maquina-js/maquina-list.js' %}"></script>

{% endblock %}

AirTecFugas/MainApp/templates/MainApp/Maquina/update-partial-maquina.html
<form id="idFormPartialEditMaquina" name="FormPartialEditMaquina" action="{% url 'maquina-partial-edit' object.pk %}" method="post">
    <div id="GenericModalHeader" class="modal-header">
	    <h5 class="modal-title" id="GenericModalTitle">Editar M&aacute;quina</h5>
	    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
		    <span aria-hidden="true">×</span>
	    </button>
    </div>
    <div id="GenericModalBody" class="modal-body">
        <div class="row gutters">
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_nombre">Nombre:</label>
                            <input type="text" name="nombre" value="{{ object.nombre }}" class="form-control" maxlength="50" required="" id="id_nombre">
                        </div>
                        <div class="form-group">
                            <label for="id_descripcion">Descripción:</label>
                            <textarea name="descripcion" cols="40" rows="10" class="form-control" style="resize:none;" maxlength="255" id="id_descripcion">{{ object.descripcion|default_if_none:"" }}</textarea>
                        </div>
                        <div class="form-group">
                            <label for="id_area">&Aacute;rea:</label>
                            <select name="area" class="form-control" required="" id="id_area" data-value="{{ object.area.id }}" data-emptylabel="Seleccione la máquina...">
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="GenericModalFooter" class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">
            <i class="icon-cancel-outline"></i>&nbsp;Cancelar
        </button>
		<button type="submit" class="btn btn-primary"><i class="icon-save2"></i>&nbsp; Guardar M&aacute;quina </button>
    </div>
</form>